// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyycdphccgphsbzkmmxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eWNkcGhjY2dwaHNiemttbXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTY1ODEsImV4cCI6MjA1ODA3MjU4MX0._7bqp4Z3Wuj9WOp75W6RzymCKjEWxXjXAE4zCGjCpxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);